# ワークフローの名前
name: Deploy TypingCRUD

# v1というタグを付けると発火
on:
  push:
    tags:
      - v1

# ジョブの定義
jobs:
  build:
    # 実行するインスタンス
    runs-on: ubuntu-latest

    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ['8.x']

    # 各ステップの実行
    steps:

    # チェックアウト
    - uses: actions/checkout@v2

    # 使用するnodeのバージョンを指定
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # パッケージのインストールとアプリのビルド
    - name: install and build
      run:
        yarn install
        yarn pro_build
      env:
        API_URL: ${{ secrets.API_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        IDENTITY_POOL_ID: ${{ secrets.IDENTITY_POOL_ID }}
        USER_POOL_ID: ${{ secrets.USER_POOL_ID }}

    # S3へデプロイ
    - name: deploy S3
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
